### ISSUE TITLE
Wrong signs for CHF

### ISSUE THREAD

**Issue by valli-org** [Commercie/currency#2]
The sign for CHF (Swiss franc) is Fr. or SFr. or FS and not ₣ as mentioned in currency/resources/currency/CHF.yml.

See also: https://en.wikipedia.org/wiki/Swiss_franc

You can find a patch here:
https://www.drupal.org/node/2549289

**Comment by bartfeenstra** [comment]
Can you please file a pull request?

**Comment by valli-org** [comment]
Pull request finally done.
